
name: bingodfok.github.io

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: ["20.13.1"]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    steps:
    - name: checkout-master
      uses: actions/checkout@v4
    - name: build with node@v${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run build --if-present
